name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.32.3
  - pip=20.3.3
  - mlflow=2.15.1
  - hydra-core=1.0.6
  - scikit-learn=1.5.1
  - pip:
      - wandb==0.10.21
      - hydra-joblib-launcher==1.1.2
